@baseUrl = http://localhost:3000

# @name fetch_todos
GET {{baseUrl}}/todos
Content-Type: application/json

###

# @name get_todo
GET {{baseUrl}}/todos/c47ef239-c02d-4929-8fdf-2a8e586b8ad1
Content-Type: application/json

###

# @name create_todo
POST {{baseUrl}}/todos
Content-Type: application/json

{
  "title": "Fazer café com leite",
  "description": "fazer café da tarde para comer com pao de queijo e requeijao"
}

###

# @name update_todo
PUT {{baseUrl}}/todos/c47ef239-c02d-4929-8fdf-2a8e586b8ad1
Content-Type: application/json

{
  "title": "Criar CRUD nest",
  "description": "criar CRUD nest respeitando todos os padrões de arquitetura"
}

###

# @name delete_todo
DELETE {{baseUrl}}/todos/c47ef239-c02d-4929-8fdf-2a8e586b8ad1
Content-Type: application/json
